### ISSUE TITLE
Doesn't build against node 7

### ISSUE THREAD

**Issue by chearon** [Automattic/node-canvas#1317]
## Issue or Feature
Ran into this doing the prebuilds. 2.2.0 doesn't build in Node 7 on any of the 3 platforms. Node 6 does. Should we add all versions to the build matrix?

## Steps to Reproduce
* `npm install` in the repo
* `src/CanvasRenderingContext2d.cc:1722:49: error: no member named 'InstanceOf' in 'v8::Object'`

Looks like it was caused by #1293 ([this line](https://github.com/Automattic/node-canvas/blob/master/src/CanvasRenderingContext2d.cc#L1722)). Should it be `> 7` instead?

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.2.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): any

**Comment by chearon** [comment]
BTW still none of the 2.x build on node 6 / macOS either, although I've never tried to find out why:

```
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Hakerh400** [comment]
> Should it be > 7 instead?

Seems correct. I'll open PR.
