### ISSUE TITLE
Unable to build on OS X 10.9.1 with latest dev tools

### ISSUE THREAD

**Issue by sanfords** [Automattic/node-canvas#372]
I am attempting to follow the instructions for installing node-canvas on OS X (https://github.com/LearnBoost/node-canvas/wiki/Installation---OSX)  and am getting linker errors even in the first section under `pkg-config`: 'duplicate symbols for architecture x86_64'.

Has anyone been successful following these instructions on the latest mavericks with the latest Xcode and latest (Oct 2013) CLI tools?  I don't know what I'm missing.

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
