### ISSUE TITLE
ctx.canvas.setAttribute/getAttribute is not a function when running in node.js

### ISSUE THREAD

**Issue by jimjiang07** [Automattic/node-canvas#2012]
## Issue or Feature
I am currently trying to upgrade Fabric.js from 4.4.0 to the newer versions of Fabric. However, I notice that when upgrading Fabric.js to 4.5.0+ or 5.0.0+, I am getting some `not a function` errors for Fabric.Text.

I had a look at the source code. Starting from 4.5.0, `ctx.canvas.setAttribute` and `ctx.canvas.getAttribute` are used in Fabric.Text for RTL text. But I think these functions are not supported in node-canvas. 

## Error
```
stack: 'TypeError: ctx.canvas.setAttribute is not a function\n' +
    '    at klass._renderChars (/app/node_modules/fabric/dist/fabric.js:26526:20)\n' +
    '    at klass._renderTextLine (/app/node_modules/fabric/dist/fabric.js:26086:12)\n' +
    '    at klass._renderTextCommon (/app/node_modules/fabric/dist/fabric.js:26451:14)\n' +
    '    at klass._renderTextFill (/app/node_modules/fabric/dist/fabric.js:26473:12)\n' +
    '    at klass._renderText (/app/node_modules/fabric/dist/fabric.js:26035:14)\n' +
    '    at klass._render (/app/node_modules/fabric/dist/fabric.js:26023:12)\n' +
    '    at klass.callSuper (/app/node_modules/fabric/dist/fabric.js:2939:22)\n' +
    '    at klass._render (/app/node_modules/fabric/dist/fabric.js:27803:12)\n' +
    '    at klass._render (/app/node_modules/fabric/dist/fabric.js:2893:52)\n' +
    '    at klass.drawObject (/app/node_modules/fabric/dist/fabric.js:15305:12)',
```

## Your Environment
Fabric Version:4.5.0+
Canvas Version: 2.9.1
Node.js version 14.17.0

**Comment by ggolda** [comment]
@jimjiang07 have you been able to resolve this issue and how?
