### ISSUE TITLE
Symbol not found:

### ISSUE THREAD

**Issue by bcbroom** [Automattic/node-canvas#1284]
trying to run the test code

```
const { createCanvas, loadImage } = require('canvas')
const canvas = createCanvas(200, 200)
const ctx = canvas.getContext('2d')

// Write "Awesome!"
ctx.font = '30px Impact'
ctx.rotate(0.1)
ctx.fillText('Awesome!', 50, 100)

// Draw line under text
var text = ctx.measureText('Awesome!')
ctx.strokeStyle = 'rgba(0,0,0,0.5)'
ctx.beginPath()
ctx.lineTo(50, 102)
ctx.lineTo(50 + text.width, 102)
ctx.stroke()

// Draw cat with lime helmet
loadImage('lime-cat.jpg').then((image) => {
  ctx.drawImage(image, 50, 0, 70, 70)

  console.log('<img src="' + canvas.toDataURL() + '" />')
})
```

## Issue or Feature
```
Brian-Secondary-MBP:clifford-node broom$ node test.js
dyld: lazy symbol binding failed: Symbol not found: __ZN2v87Isolate19CheckMemoryPressureEv
  Referenced from: /Users/broom/Documents/code/procGeometry/clifford-node/node_modules/canvas/build/Release/canvas.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v87Isolate19CheckMemoryPressureEv
  Referenced from: /Users/broom/Documents/code/procGeometry/clifford-node/node_modules/canvas/build/Release/canvas.node
  Expected in: flat namespace

Abort trap: 6
```

## Steps to Reproduce
run the above

## Your Environment
node-canvas - 2.0.1

node 8.11.3 on macOS 10.13.6

I also tried in another folder with node-canvas 1.6.12, which worked

**Comment by nick-jonas** [comment]
Same problem too...
Node: v8.9.1
MacOS: 10.13.6
canvas: 2.0.1

**Comment by zbjornson** [comment]
@mostalt @nick-jonas @bcbroom  not sure if you saw my comment above since GitHub was having issues. Does Node.js v8.12.0 work for you?

**Comment by ColeT3tr3x** [comment]
I had this issue, Fixed it by upgrading to latest NodeJS stable.

**Comment by bcbroom** [comment]
@zbjornson yep - node 8.12.0 works, thanks for the suggestion.

**Comment by mostalt** [comment]
@zbjornson works fine after update node to 10.5.0, thx.

**Comment by TooMuchRAM** [comment]
For me, it doesn't work with 10.5.0. It also doesn't work with 10.15.1. All I do is `const { createCanvas, loadImage } = require('canvas')`. Am I doing something wrong? Using NVM.
