### ISSUE TITLE
Missing preprocessor directives in Canvas.cc for when libjpeg isn't available

### ISSUE THREAD

**Issue by zbjornson** [Automattic/node-canvas#1196]
I broke this in #1152 probably.

```
../src/Canvas.cc: In static member function ‘static void Canvas::ToJpegBufferAsync(uv_work_t*)’:
../src/Canvas.cc:209:90: error: ‘write_to_jpeg_buffer’ was not declared in this scope
   write_to_jpeg_buffer(closure->canvas->surface(), closure, &closure->data, &closure->len);
```
