### ISSUE TITLE
Canvas is not builded with new iojs 3.0.0 it works on v2.5

### ISSUE THREAD

**Issue by igorzg** [Automattic/node-canvas#607]
```javascript
../src/libsass/json.cpp: In function 'bool parse_string(const char**, char**)':
../src/libsass/json.cpp:110:51: warning: 'sb.SB::start' may be used uninitialized in this function [-Wmaybe-uninitialized]
   sb->start = (char*) realloc(sb->start, alloc + 1);
                                                   ^
../src/libsass/json.cpp:823:6: note: 'sb.SB::start' was declared here
   SB sb;
      ^
../src/libsass/json.cpp:97:19: warning: 'sb.SB::end' may be used uninitialized in this function [-Wmaybe-uninitialized]
     if ((sb)->end - (sb)->cur < (need))     \
                   ^
../src/libsass/json.cpp:823:6: note: 'sb.SB::end' was declared here
   SB sb;
      ^
../src/libsass/json.cpp:138:85: warning: 'sb.SB::cur' may be used uninitialized in this function [-Wmaybe-uninitialized]
   assert(sb->start <= sb->cur && strlen(sb->start) == (size_t)(sb->cur - sb->start));
                                                                                     ^
../src/libsass/json.cpp:823:6: note: 'sb.SB::cur' was declared here
   SB sb;
      ^
In file included from ../src/binding.cpp:1:0:
../node_modules/nan/nan.h:324:27: error: redefinition of 'template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)'
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: error: 'template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)' previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of 'template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)'
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: error: 'template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)' previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: 'node::smalloc' has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ',' or '...' before 'callback'
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)':
../node_modules/nan/nan.h:761:50: error: 'callback' was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: 'hint' was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)':
../node_modules/nan/nan.h:768:67: error: call of overloaded 'New(v8::Isolate*, const char*&, uint32_t&)' is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/binding.cpp:1:

**Comment by LinusU** [comment]
Duplicate of #606
