### ISSUE TITLE
npm install canvas - latest version not working on ubuntu 14.04

### ISSUE THREAD

**Issue by dorin2006** [Automattic/node-canvas#598]
make: Entering directory /home/mark/Programming/canvas_npm/node_modules/canvas/build' SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node COPY Release/canvas-postbuild.node CXX(target) Release/obj.target/canvas/src/Canvas.o In file included from ../src/Canvas.cc:7:0: ../src/Canvas.h:22:17: fatal error: nan.h: No such file or directory #include <nan.h> ^ compilation terminated. make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1 make: Leaving directory/home/mark/Programming/canvas_npm/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: make failed with exit code: 2

**Comment by LinusU** [comment]
This is because of #596

**Comment by LinusU** [comment]
This is fixed in version `1.2.5`
