### ISSUE TITLE
1.2.4 fails build on nan.h

### ISSUE THREAD

**Issue by arvind** [Automattic/node-canvas#588]
node-canvas v1.2.4 was just released but it's failing to build on nodejs 0.10 and 0.12 for me with the following error:

```
> canvas@1.2.4 install /home/travis/build/vega/vega/node_modules/vega-scenegraph/node_modules/canvas
> node-gyp rebuild
make: Entering directory `/home/travis/build/vega/vega/node_modules/vega-scenegraph/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node: Finished
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:7:0:
../src/Canvas.h:22:17: fatal error: nan.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
make: Leaving directory `/home/travis/build/vega/vega/node_modules/vega-scenegraph/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/v0.10.40/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "node" "/home/travis/.nvm/v0.10.40/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/vega/vega/node_modules/vega-scenegraph/node_modules/canvas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
```

**Comment by arvind** [comment]
This has broken our Travis CI build (https://travis-ci.org/vega/vega/builds/72344251). I'm wondering if some additional dependencies need to be included or added to .travis.yml that have been introduced since v1.2.3?

**Comment by mathiasbynens** [comment]
Same issue here. This breaks io.js v2.4.0 as well.

**Comment by jheer** [comment]
There are discrepancies in `binding.gyp` between the github repo and the version published on npm. In particular, this segment appears to clobber the earlier `include_dirs` directive, preventing the inclusion of nan.h:
```
      'include_dirs': [
        '/opt/X11/include',
      ],
      'library_dirs': [
        '/opt/X11/lib',
      ],
```
If you remove these additions, canvas builds without issue for me. Similarly, the github version builds fine for me. Perhaps an errant edit made it into the file prior to `npm publish`?

**Comment by Crotery** [comment]
+1, 1.2.4 fails, 1.2.3 npm install ok

**Comment by arusakov** [comment]
+1, Mac OS X 1.2.4 fails, 1.2.3 ok

**Comment by frnk94** [comment]
+1 Same issue

**Comment by paulborza** [comment]
+1

**Comment by unlucio** [comment]
+1 fails for me too

**Comment by miguelmota** [comment]
+1 fails

**Comment by joemaller** [comment]
Confirming, on OS X 1.2.4 fails to install, 1.2.3 installs correctly. Rolling back for now.

**Comment by LinusU** [comment]
This is republished as `1.2.5` now, that one should work.
