### ISSUE TITLE
Instance built on Ubuntu won't work on Debian or Red Hat systems

### ISSUE THREAD

**Issue by mrsimonemms** [Automattic/node-canvas#248]
I'm having a really frustrating issue getting this integrated with our infrastructure.  The company setup is:
- Development/build on Ubuntu 12.04/12.10 machines
- Testing on Debian machines
- Live on RedHat machines
  All machines are 64 bit.

When we build and release to the Debian/RedHat machines, we always get the following error:

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module '../build/default/canvas'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/semms/staging/node_modules/canvas/lib/bindings.js:7:20)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
```

At first, we assumed that there was some architecture issue as per #184, but have subsequently proven this not to be the case and that all machines are indeed running 64 bit builds of NodeJS.  What we have noticed is that this is only an issue when deploying to a Debian/RedHat machine - we have some Ubuntu machines in the office and, when we deploy to that, it works first time.

Next, we looked at #216 and updated our PATH and LD_LIBRARY_PATH.  However, this has again not worked.

What is particularly confusing is that, if we build everything on the Debian/RedHat box and deploy to anything else (including Ubuntu), it all works.  We're therefore assuming that there is something that is some difference between the Debian/RedHat setup compared to the Ubuntu one but cannot identify what this is.

Can someone help shed some light onto that issue?

Thanks
## Setup
- NodeJS 0.6.12
- Canvas 0.10.2
