### ISSUE TITLE
Fails to build with io.js on linux

### ISSUE THREAD

**Issue by janza** [Automattic/node-canvas#520]
Hi, I've seen that 1.2.0 supports io.js so I tried using it but I'm getting 
```‘_isnan’ was not declared in this scope```, and ```’_finite’ was not declared in this scope``` errors.
It builds fine with node 0.10 though.
Here's the complete log: http://pastebin.com/v3kr2bc5

**Comment by skerit** [comment]
Yeah, I had the same error on iojs 1.1.0 and 1.2.0.
