### PR TITLE
Upgrade NAN to v2

### PR DESCRIPTION
**Pull request by rvagg**

### CODE REVIEW

**Comment by rvagg** [comment]
Sorry, empty description meant to say:

NAN v2 isn't released yet so this is a WIP, not intended to be merged. NAN v2 is a major rewrite that is forward compatible to V8 4.5 so it support io.js v3 which is in RC at the moment while we get NAN v2 out (because _everything_ is broken thanks to V8 43 and 4.4). This version of NAN should also give us automatic support for Node.js v4 (most likely version, could be v5 though) when it comes out in a few months.

I'll update here when NAN is released and this is ready to merge. There's currently a bug holding this up from passing all the tests and NAN v2 isn't in npm yet either.

**Comment by rvagg** [comment]
```
../src/PixelArray.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE PixelArray::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/PixelArray.cc:69:16: error: ‘class v8::Object’ has no member named ‘SetIndexedPropertiesToPixelData’
   info.This()->SetIndexedPropertiesToPixelData(
                ^
../src/PixelArray.cc: In static member function ‘static Nan::NAN_GETTER_RETURN_TYPE PixelArray::GetLength(v8::Local<v8::String>, Nan::NAN_GETTER_ARGS_TYPE)’:
../src/PixelArray.cc:83:59: error: ‘class v8::Object’ has no member named ‘GetIndexedPropertiesPixelDataLength’
   info.GetReturnValue().Set(Nan::New<Number>(info.This()->GetIndexedPropertiesPixelDataLength()));
```

The `IndexedProperties*PixelData*()` API is gone in V8 4.4 (and maybe 4.3?) so it doesn't compile on io.js next (3.0.0 RC). @kkoopa, @bnoordhuis, @trevnorris anyone got any suggestions here? I've got no idea what to replace this with.

**Comment by bnoordhuis** [comment]
There is no direct replacement.  You could attach a node::Buffer or v8::TypedArray as a hidden property.  Typed arrays won't work with v0.10 though, a Buffer is more portable.

**Comment by trevnorris** [comment]
@bnoordhuis Though that would present a minor change in API, since the CanvasPixelArray is clamped, but Uint8Array is not.

**Comment by bnoordhuis** [comment]
Good point.  You'd have to use v8::Uint8ClampedArray in that case and guard with #ifdefs.

**Comment by rvagg** [comment]
OK, this is getting a bit out of hand for what I have time for so I'm going to have to put this on the backburner and ask that anyone here who wants node-canvas to work with io.js 3.0 and beyond (including the next Node) can pick up from this branch if they want and work with that.

**Comment by micky2be** [comment]
Looking forward

**Comment by rvagg** [comment]
this needs help from someone with the time to grok what's required in order to bring back the support that was lost with the removal of the relevant V8 APIs mentioned above

**Comment by kkoopa** [comment]
It's being done. https://github.com/Automattic/node-canvas/pull/604

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by LinusU** [comment]
Superseded by another pull request that got merged

**Comment by mathiasbynens** [comment]
> Superseded by another pull request that got merged

For future reference, that PR was #622.

**Comment by LinusU** [comment]
Thank you :+1:
