### PR TITLE
Define correct isnan, isinf functions

### LINKED ISSUE #520: Fails to build with io.js on linux
Hi, I've seen that 1.2.0 supports io.js so I tried using it but I'm getting 
```‘_isnan’ was not declared in this scope```, and ```’_finite’ was not declared in this scope``` errors.
It builds fine with node 0.10 though.
Here's the complete log: http://pastebin.com/v3kr2bc5

### PR DESCRIPTION
**Pull request by janza**
fixes #520

### CODE REVIEW

**Comment by janza** [comment]
This PR fixes building node-canvas on linux with io.js. I've also added travis io.js target to confirm that it's working.

**Comment by rvagg** [comment]
Using an io.js branch of [dnt](https://github.com/rvagg/dnt/pull/14):

```
~/git/node-canvas $ dnt
node@v0.11.16: PASS wrote output to /tmp/canvas-dnt-v0.11.16.out
node@v0.10.36: PASS wrote output to /tmp/canvas-dnt-v0.10.36.out
node@v0.12.0 : PASS wrote output to /tmp/canvas-dnt-v0.12.0.out
iojs@v1.1.0  : FAIL wrote output to /tmp/canvas-dnt-v1.1.0.out
iojs@v1.0.0  : FAIL wrote output to /tmp/canvas-dnt-v1.0.0.out
iojs@v1.2.0  : FAIL wrote output to /tmp/canvas-dnt-v1.2.0.out
Took 462s to run 6 versions of Node
[rvagg@fletcher (master) ~/git/node-canvas]$ curl https://github.com/Automattic/node-canvas/pull/522.patch | git am
Applying: define correct isnan, isinf functions
Applying: run travis tests against io.js
~/git/node-canvas $ dnt
node@v0.10.36: PASS wrote output to /tmp/canvas-dnt-v0.10.36.out
node@v0.11.16: PASS wrote output to /tmp/canvas-dnt-v0.11.16.out
node@v0.12.0 : PASS wrote output to /tmp/canvas-dnt-v0.12.0.out
iojs@v1.1.0  : PASS wrote output to /tmp/canvas-dnt-v1.1.0.out
iojs@v1.0.0  : PASS wrote output to /tmp/canvas-dnt-v1.0.0.out
iojs@v1.2.0  : PASS wrote output to /tmp/canvas-dnt-v1.2.0.out
Took 493s to run 6 versions of Node
```

so :thumbsup: from me!

**Comment by jomo** [comment]
Pulled and tested (dokku & travis), issue indeed fixed.
:+1: from me as well

**Comment by kangax** [comment]
Great, thanks everyone, merging!
