### ISSUE TITLE
problem while installing node canvas in centos

### ISSUE THREAD

**Issue by webhav** [Automattic/node-canvas#329]
Hi all,

I am trying to npm install canvas, and getting below output :+1: 

[app-tm-001@localhost ~]$ clear
[app-tm-001@localhost ~]$ npm install canvas
npm http GET https://registry.npmjs.org/canvas
npm http 304 https://registry.npmjs.org/canvas

> canvas@1.1.0 install /home/app-tm-001/node_modules/canvas
> node-gyp rebuild

make: Entering directory `/home/app-tm-001/node_modules/canvas/build'
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:8:
../src/PNG.h: In function â€˜cairo_status_t canvas_write_png(cairo_surface_t*, void (*)(png_struct*, png_byte*, png_size_t), void*)â€™:
../src/PNG.h:139: error: â€˜CAIRO_FORMAT_RGB30â€™ was not declared in this scope
../src/PNG.h:158: error: â€˜CAIRO_FORMAT_INVALIDâ€™ was not declared in this scope
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
make: Leaving directory`/home/app-tm-001/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 2.6.32-279.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/app-tm-001/node_modules/canvas
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

I looked into other similar issues, but those where mainly focussed on OSX. I am working on centos 6.3

Note : I have already installed node-gyp. 

Please help.

**Comment by stuartZhang** [comment]
I have ever stumbled across the same issue as vaibhaviitd for the latest version 1.3.4 in CentOS.

As of this writing, I have to be stuck to the version 1.1.6 in CentOS.

However, I have discovered the same issue has been resolved in Ubuntu. See also: https://github.com/Automattic/node-canvas/wiki/Installation---Ubuntu-and-other-Debian-based-systems#installing-dependencies

My question: Is there the solution similar to the above but serving CentOS?
