### ISSUE TITLE
Does not build with node 0.10.4 on linux?

### ISSUE THREAD

**Issue by remoe** [Automattic/node-canvas#273]
node-canvas does not build on node 0.10.4:

``` c++
  CXX(target) Release/obj.target/canvas/src/Canvas.o
../src/Canvas.cc: In static member function 'static v8::Handle<v8::Value> Canvas::ToBuffer(const v8::Arguments&)':
../src/Canvas.cc:261:76: error: invalid conversion from 'void (*)(uv_work_t*)' to 'void (*)(uv_work_t*, int)'
../src/Canvas.cc:261:76: error:   initializing argument 4 of 'int uv_queue_work(uv_loop_t*, uv_work_t*, void (*)(uv_work_t*), void (*)(uv_work_t*, int))'
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1

...
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
```

but it works with node 0.8.23
