### ISSUE TITLE
Publish version 2.9.1 with Typescript 4.6 compatibility?

### ISSUE THREAD

**Issue by Rush** [Automattic/node-canvas#2007]
```
node_modules/canvas/types/index.d.ts(170,2): error TS2416: Property 'globalCompositeOperation' in type 'NodeCanvasRenderingContext2D' is not assignable to the same property in base type 'CanvasRenderingContext2D'.
````

Fixed by commit: https://github.com/Automattic/node-canvas/commit/6fd0fa55343aa244e7097f6ee50b271a8636ee63 but it needs releasing

**Comment by zbjornson** [comment]
Releases are stuck because of troubles making the prebuilds unfortunately (https://github.com/Automattic/node-canvas/pull/1987#issuecomment-1051569116). I haven't had a chance to resume debugging since I posted that comment.

**Comment by Rush** [comment]
Sorry to hear about the troubles. In the meantime I published a one-line fix over 2.9.0. To install, replace your version with the string below:
```
    "canvas": "Rush/node-canvas#v2.9.0-patched",
```

This is the only difference between 2.9.0 https://github.com/Rush/node-canvas/blob/636e4dbc0a18a5861d77620b3658b944f778691e/types/index.d.ts#L170 - I think since binary versions depend on the published version everything should work the same, with the exception this one works with Typescript 4.6

**Comment by zbjornson** [comment]
v2.9.1 is now published.
