### ISSUE TITLE
Install error on Mac OS X with 1.1.0 (works with 1.0.4)

### ISSUE THREAD

**Issue by mwawrusch** [Automattic/node-canvas#314]
Hi guys, got this:

  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:8:
../src/PNG.h:139:10: error: use of undeclared identifier 'CAIRO_FORMAT_RGB30'
    case CAIRO_FORMAT_RGB30:
         ^
1 error generated.
